Repository tazama-lf/admin-service, pull requests merged in 2024-10, with the labels that each got.

#110 fix: validate extra push date of month calendar
  __tests__/unit/app.eventFlow.test.ts
  __tests__/unit/test.data.ts
  src/utils/condition-validation.ts
Labels: bug

#111 feat: env validation
  .env.template
  Dockerfile
  __tests__/unit/app.eventFlow.test.ts
  package-lock.json
  package.json
  src/config.ts
Labels: enhancement

#117 refactor: split cache options env vars
  .env.template
  Dockerfile
  package-lock.json
  package.json
  src/config.ts
Labels: refactor

#123 refactor: abstract services
  .env.template
  Dockerfile
  __tests__/unit/app.eventFlow.test.ts
  package-lock.json
  package.json
  src/app.controller.ts
  src/config.ts
  src/index.ts
  src/services/event-flow.logic.service.ts
  src/utils/schema-utils.ts
Labels: refactor
